const s2c_protocol_max = 9999999;
const C2S_PROTOCOL_MIN = 1000
const C2S_PROTOCOL_MAX = 5000
const S2C_PROTOCOL_MIN = 20000
const S2C_PROTOCOL_MAX = 24000
enum C2S_PROTOCOL {
	c2s_login = 1000 ,
	c2s_close_game = 1001 ,
	c2s_room_create = 1002 ,
	c2s_room_join = 1003 ,
	c2s_room_start_game = 1004 ,
	c2s_room_restart_room = 1005 ,
	c2s_room_gameover_report = 1006 ,
	c2s_room_close = 1007 ,
	c2s_store_list = 1008 ,
	c2s_store_buy = 1009 ,
	c2s_store_item_buy = 1010 ,
	c2s_player_info = 1011 ,
	c2s_leave_game = 1012 ,
	c2s_heartbeat = 1013 ,
	c2s_client_log = 1014 ,
	c2s_arena_list = 1200 ,
	c2s_join_arena = 1201 ,
	c2s_query_live_config = 1400 ,
	c2s_create_live_game = 1401 ,
	c2s_join_live_game = 1402 ,
	c2s_start_live_game = 1403 ,
	c2s_leave_live_game = 1404 ,
	c2g_out_card = 3000 ,
	c2g_touch_card = 3001 ,
	c2g_blocked_round = 3002 ,
	c2g_request_exchange_card = 3003 ,
	c2g_exchange_card = 3004 ,
}

enum S2C_PROTOCOL {
	g2c_game_data = 22000 ,
	g2c_draw_card = 22001 ,
	g2c_hand_card = 22002 ,
	g2c_boardcast_remain_card = 22003 ,
	g2c_boardcast_turner_id = 22004 ,
	g2c_boardcast_account_out_card = 22005 ,
	g2c_boardcast_draw_card = 22006 ,
	g2c_boardcast_game_group_result = 22007 ,
	g2c_boardcast_game_result = 22008 ,
	g2c_boardcast_outcard_point_reward = 22009 ,
	g2c_boardcast_notice = 22010 ,
	g2c_start_game = 22011 ,
	g2c_boardcast_blocked_round = 22012 ,
	g2c_boardcast_start_count_time = 22013 ,
	g2c_boardcast_account_offline = 22014 ,
	g2c_boardcast_account_trust = 22015 ,
	g2c_exchange_failed = 22016 ,
	g2c_exchange_success = 22017 ,
	g2c_refresh_account_exchange = 22018 ,
	g2c_exchange_timer = 22019 ,
	s2c_login = 20000 ,
	s2c_game_state = 20001 ,
	s2c_room_create = 20002 ,
	s2c_room_join = 20003 ,
	s2c_room_info = 20004 ,
	s2c_room_start_game = 20005 ,
	s2c_room_restart_room = 20006 ,
	s2c_room_gameover_report = 20007 ,
	s2c_room_close = 20008 ,
	s2c_store_list = 20009 ,
	s2c_store_buy = 20010 ,
	s2c_store_item_buy = 20011 ,
	s2c_player_info = 20012 ,
	s2c_error = 20013 ,
	s2c_group_result = 20014 ,
	s2c_group_result_visits = 20015 ,
	s2c_arena_list = 20200 ,
}

const PROTOCOL_CMD2NAME = [];
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_login] = "c2s_login";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_close_game] = "c2s_close_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_room_create] = "c2s_room_create";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_room_join] = "c2s_room_join";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_room_start_game] = "c2s_room_start_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_room_restart_room] = "c2s_room_restart_room";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_room_gameover_report] = "c2s_room_gameover_report";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_room_close] = "c2s_room_close";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_store_list] = "c2s_store_list";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_store_buy] = "c2s_store_buy";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_store_item_buy] = "c2s_store_item_buy";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_player_info] = "c2s_player_info";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_leave_game] = "c2s_leave_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_heartbeat] = "c2s_heartbeat";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_client_log] = "c2s_client_log";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_arena_list] = "c2s_arena_list";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_join_arena] = "c2s_join_arena";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_query_live_config] = "c2s_query_live_config";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_create_live_game] = "c2s_create_live_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_join_live_game] = "c2s_join_live_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_start_live_game] = "c2s_start_live_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2s_leave_live_game] = "c2s_leave_live_game";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2g_out_card] = "c2g_out_card";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2g_touch_card] = "c2g_touch_card";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2g_blocked_round] = "c2g_blocked_round";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2g_request_exchange_card] = "c2g_request_exchange_card";
PROTOCOL_CMD2NAME[C2S_PROTOCOL.c2g_exchange_card] = "c2g_exchange_card";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_game_data] = "g2c_game_data";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_draw_card] = "g2c_draw_card";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_hand_card] = "g2c_hand_card";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_remain_card] = "g2c_boardcast_remain_card";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_turner_id] = "g2c_boardcast_turner_id";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_account_out_card] = "g2c_boardcast_account_out_card";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_draw_card] = "g2c_boardcast_draw_card";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_game_group_result] = "g2c_boardcast_game_group_result";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_game_result] = "g2c_boardcast_game_result";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_outcard_point_reward] = "g2c_boardcast_outcard_point_reward";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_notice] = "g2c_boardcast_notice";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_start_game] = "g2c_start_game";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_blocked_round] = "g2c_boardcast_blocked_round";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_start_count_time] = "g2c_boardcast_start_count_time";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_account_offline] = "g2c_boardcast_account_offline";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_boardcast_account_trust] = "g2c_boardcast_account_trust";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_exchange_failed] = "g2c_exchange_failed";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_exchange_success] = "g2c_exchange_success";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_refresh_account_exchange] = "g2c_refresh_account_exchange";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.g2c_exchange_timer] = "g2c_exchange_timer";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_login] = "s2c_login";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_game_state] = "s2c_game_state";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_create] = "s2c_room_create";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_join] = "s2c_room_join";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_info] = "s2c_room_info";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_start_game] = "s2c_room_start_game";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_restart_room] = "s2c_room_restart_room";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_gameover_report] = "s2c_room_gameover_report";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_room_close] = "s2c_room_close";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_store_list] = "s2c_store_list";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_store_buy] = "s2c_store_buy";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_store_item_buy] = "s2c_store_item_buy";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_player_info] = "s2c_player_info";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_error] = "s2c_error";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_group_result] = "s2c_group_result";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_group_result_visits] = "s2c_group_result_visits";
PROTOCOL_CMD2NAME[S2C_PROTOCOL.s2c_arena_list] = "s2c_arena_list";
